Add WAF workflows and template
alphagov/di-ipv-cri-cic-api pull request #83
Opened 2023-03-06 14:51 UTC by devdutoitGDS

## Proposed changes
Add WAF github actions workflows for DEV and BUILD
Add WAF template

### Why did it change

### Issue tracking

- [F2F-XXX](https://govukverify.atlassian.net/browse/F2F-XXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-03-06 14:53 UTC, andyloughran requested changes
Please can you also copy the README.md file next to the template.

2023-03-06 14:59 UTC, andyloughran approved these changes

2023-03-06 15:00 UTC, andyloughran commented
@devdutoitGDS did I also have some jest tests on the branch?  Can we move them over too, and have them executing as part of the workflow?

2023-03-09 15:23 UTC, darrendunford approved these changes

2023-03-13 09:51 UTC, andyloughran approved these changes
Looks good.

2023-03-13 10:15 UTC, merged